# Generated by Django 5.2.9 on 2025-12-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название Корабля')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('crew', models.IntegerField(verbose_name='Экипаж')),
                ('passengers', models.IntegerField(verbose_name='Пассажиры')),
                ('hyperdrive_rating', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Рейтинг гипердрайва')),
            ],
            options={
                'verbose_name': 'Корабль',
                'verbose_name_plural': 'Корабли',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя Персонажа')),
                ('height', models.IntegerField(verbose_name='Рост (см)')),
                ('mass', models.IntegerField(verbose_name='Масса (кг)')),
                ('hair_color', models.CharField(max_length=50, verbose_name='Цвет волос')),
                ('skin_color', models.CharField(max_length=50, verbose_name='Цвет кожи')),
                ('eye_color', models.CharField(max_length=50, verbose_name='Цвет глаз')),
                ('birth_year', models.CharField(max_length=20, verbose_name='Год рождения')),
                ('gender', models.CharField(max_length=50, verbose_name='Пол')),
                ('starship', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starwars.starship', verbose_name='Собственный Корабль')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['name'],
            },
        ),
    ]
