# Generated by Django 5.2.9 on 2025-12-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='mass',
            field=models.IntegerField(blank=True, null=True, verbose_name='Масса (кг)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='starship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilots', to='starwars.starship', verbose_name='Собственный Корабль / Принадлежащий Корабль'),
        ),
        migrations.AlterField(
            model_name='starship',
            name='crew',
            field=models.IntegerField(blank=True, null=True, verbose_name='Экипаж'),
        ),
        migrations.AlterField(
            model_name='starship',
            name='hyperdrive_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Рейтинг гипердрайва'),
        ),
        migrations.AlterField(
            model_name='starship',
            name='passengers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пассажиры'),
        ),
    ]
